// Browser UltraHonk prover for `move_along` (M8.5): witness inputs are
// computed HERE (Poseidon2 commitments + edge-tree path), the ACVM witness
// is solved by noir_js, and the proof is generated by bb.js with the SAME
// scheme/oracle the CLI pipeline pins (`ultra_honk` + `keccak`) — so the
// on-chain verifier accepts browser proofs and CLI proofs alike (proven by
// the CLI-parity test).
//
// Everything here is browser-pure: no Node imports. The caller supplies the
// compiled circuit artifact, the VK, and the (public) graph data — in the
// web app those are served as static assets.

import { UltraHonkBackend } from "@aztec/bb.js";
import { Noir } from "@noir-lang/noir_js";
import type { CompiledCircuit } from "@noir-lang/noir_js";
import { initPoseidon, poseidon2, toBe32Blob, toBe32Hex } from "./fields.js";
import { buildEdgeTree, merklePath } from "./graph.js";
import type { EdgeTree, GraphData } from "./graph.js";

export type WebBoardProof = {
  /** UltraHonk proof bytes (14592) — hex these into `submit_hidden_move`. */
  proof: Uint8Array;
  /** c_old | c_new | ticket | root (128 bytes) — the verifier's public-inputs blob. */
  publicInputs: Uint8Array;
  cOldHex: string;
  cNewHex: string;
  rootHex: string;
  ticket: number;
};

export type WebProverArtifacts = {
  /** The compiled `move_along` ACIR artifact (target/move_along.json, parsed). */
  circuit: CompiledCircuit;
  /** The public city graph (same JSON `zktable-graph` consumes). */
  graph: GraphData;
};

export type WebBoardProver = {
  /** Poseidon2(node, salt) as 32-byte hex — hidden-position commitments. */
  commit(node: number, salt: bigint): string;
  /** The edge-tree root as 32-byte hex (per-map public constant). */
  root(): string;
  /** Prove one hidden move. The secret (from/to/salts) never leaves the caller. */
  prove(move: { from: number; to: number; ticket: 0 | 1 | 2; saltOld: bigint; saltNew: bigint }): Promise<WebBoardProof>;
  /** Local verification against the circuit's own (keccak) verification key. */
  verifyLocally(proof: WebBoardProof): Promise<boolean>;
};

/**
 * Builds a browser prover: initializes the Poseidon2 WASM, precomputes the
 * public edge tree, and holds a lazily-created UltraHonk backend.
 */
export async function createWebProver(artifacts: WebProverArtifacts): Promise<WebBoardProver> {
  await initPoseidon();
  const tree: EdgeTree = buildEdgeTree(artifacts.graph);
  const noir = new Noir(artifacts.circuit);
  const backend = new UltraHonkBackend(artifacts.circuit.bytecode);

  return {
    commit(node: number, salt: bigint): string {
      return toBe32Hex(poseidon2(BigInt(node), salt));
    },

    root(): string {
      return toBe32Hex(tree.root);
    },

    async prove(move): Promise<WebBoardProof> {
      const cOld = poseidon2(BigInt(move.from), move.saltOld);
      const cNew = poseidon2(BigInt(move.to), move.saltNew);
      const { siblings, bits } = merklePath(tree, [move.from, move.to, move.ticket]);

      const { witness } = await noir.execute({
        c_old: cOld.toString(),
        c_new: cNew.toString(),
        ticket: String(move.ticket),
        root: tree.root.toString(),
        from: String(move.from),
        salt_old: move.saltOld.toString(),
        to: String(move.to),
        salt_new: move.saltNew.toString(),
        path_siblings: siblings.map((s) => s.toString()),
        path_bits: bits.map((b) => String(b)),
      });

      // keccak oracle hash — REQUIRED for the on-chain verifier (the same
      // flag the CLI pipeline passes as `--oracle_hash keccak`).
      const { proof } = await backend.generateProof(witness, { keccak: true });

      return {
        proof,
        publicInputs: toBe32Blob([cOld, cNew, BigInt(move.ticket), tree.root]),
        cOldHex: toBe32Hex(cOld),
        cNewHex: toBe32Hex(cNew),
        rootHex: toBe32Hex(tree.root),
        ticket: move.ticket,
      };
    },

    async verifyLocally(p: WebBoardProof): Promise<boolean> {
      const publicInputs: string[] = [];
      for (let i = 0; i < p.publicInputs.length; i += 32) {
        const word = [...p.publicInputs.slice(i, i + 32)].map((b) => b.toString(16).padStart(2, "0")).join("");
        publicInputs.push(`0x${word}`);
      }
      return backend.verifyProof({ proof: p.proof, publicInputs }, { keccak: true });
    },
  };
}
